_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": train/step
              "6":
                - 3
              "7": []
            - "1": eval/step
              "6":
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 53
                - 55
                - 71
                - 95
            "2":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 53
                - 55
                - 71
                - 95
            "3":
                - 7
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 16
effective_batch_size:
    value: 128
gradient_accumulation_steps:
    value: 8
learning_rate:
    value: 5e-06
model_path:
    value: Qwen/Qwen2.5-Math-1.5B
n_sft_examples:
    value: null
num_train_epochs:
    value: 1
